#!/usr/bin/bash

if [$# -ne 1]; then
    DATE=`date +%Y-%m-%d`
    folder="/home/data/charis/$DATE"
else
    folder=$1
fi

inotifywait -m -e create $folder | while read path action file
do
	echo "Found new filename: $file"
	tme=`./grepfits EXPTIME $path/$file | sed -n 2p | awk '{print $2;}'`
	sleep $tme	
	/home/mrclean/quicklook/code/quicklook $path/$file &
done
