#!/usr/bin/bash

folder="/home/data/charis"
echo "Watching folder $folder"
inotifywait -m -r -e create $folder | while read path action file
do
    echo "Watching folder $folder"
    # test if new file is a fits file
    if [[ "$file" =~ .*fits$ ]]; then 
        echo "Found new filename: $file"
        # find the EXPTIME keyword value in FITS file, to know how much to wait
        tme=`./grepfits EXPTIME $path/$file | sed -n 2p | awk '{print $2;}'`
        # wait for exposure to finish
        sleep $tme	
        # call the quicklook routine on the newfile
		/home/mrclean/quicklook/code/quicklook $path/$file &
	else
	    echo "$file is not a FITS file - ignoring"
	fi
done
